// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        // Fallback to web/android config for desktop platforms
        return web;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjApI27K3_a-v_J1qYdm-WZvUU2G00ReA',
    appId: '1:453928856195:android:ddcfdca98b3dd81530c9b6',
    messagingSenderId: '453928856195',
    projectId: 'rememberforme-fc18b',
    databaseURL: 'https://rememberforme-fc18b-default-rtdb.firebaseio.com',
    storageBucket: 'rememberforme-fc18b.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXOR8sYBdXYWcb1nFktWJ-mxgc9-NDbPk',
    appId: '1:453928856195:web:b074f1099dea94dc30c9b6',
    messagingSenderId: '453928856195',
    projectId: 'rememberforme-fc18b',
    databaseURL: 'https://rememberforme-fc18b-default-rtdb.firebaseio.com',
    storageBucket: 'rememberforme-fc18b.firebasestorage.app',
    authDomain: 'rememberforme-fc18b.firebaseapp.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXOR8sYBdXYWcb1nFktWJ-mxgc9-NDbPk',
    appId: '1:453928856195:ios:someplaceholder',
    messagingSenderId: '453928856195',
    projectId: 'rememberforme-fc18b',
    databaseURL: 'https://rememberforme-fc18b-default-rtdb.firebaseio.com',
    storageBucket: 'rememberforme-fc18b.firebasestorage.app',
  );
}
